### ISSUE TITLE
Access to _stringify_key (dictionary key encoding/decoding)?

### ISSUE THREAD

**Issue by JBaldachino** [simplejson/simplejson#100]
There are a lot of "hooks" built into the encoding/decoding process for the _values_ of the dictionary you are converting to/from JSON.

There are none for the _keys_ of said dictionary.  There are numerous ways to handle custom objects' encode/decode behavior: custom Encoders, `default=func`, `for_json` method. 

However, these are not applied to the _keys_ of the dictionary. 

Reviewing the source, I see a rather similar process being used on the keys that is used to process the values:

https://github.com/simplejson/simplejson/blob/master/simplejson/encoder.py#L490

``` py
    def _stringify_key(key):
        if isinstance(key, string_types): # pragma: no cover
            pass
        elif isinstance(key, binary_type):
            key = key.decode(_encoding)
        elif isinstance(key, float):
            key = _floatstr(key)
        elif key is True:
            key = 'true'
        elif key is False:
            key = 'false'
        elif key is None:
            key = 'null'
        elif isinstance(key, integer_types):
            key = str(key)
        elif _use_decimal and isinstance(key, Decimal):
            key = str(key)
        elif _skipkeys:
            key = None
        else:
            raise TypeError("key " + repr(key) + " is not a string")
        return key
```

A custom "hook" is built in here for the `Decimal` class, which is great, but why do we treat this class as special?  Is there a reason we could not expose this conversion process to extension, as we do in `default=`?  

Unfortunately, this function is buried inside another, much larger function, and there's no trivial way to swap it out, so I'm faced with some sloppy options if I want to encode a dictionary like:

`{MyObject('Something'): 10}`

Upon a very light review, it seems this could be implemented in a similar manner as the `default=` kwarg argument.  I understand there may be performance concerns, but I suppose I don't see them as any different than those opened up by the `default=` kwarg.

**Comment by mayerwin** [comment]
I agree that this should at least be better documented, but ideally an option should be available to use a custom key serializer. 
An example of non string dictionary key is a key that can easily be mapped to a string (for example a unique symbol) but which benefits, in the code, from being a more complex object.
The APIs exposed by ServiceStack.Text (for .NET) can be a good inspiration.

**Comment by mayerwin** [comment]
I am linking this patch request here for the core json library (from 2013):
https://bugs.python.org/issue18820
