### ISSUE TITLE
When running tests via nose I get ImportError

### ISSUE THREAD

**Issue by comatory** [simplejson/simplejson#117]
My app uses simplejson, everything is running in virtualenv and the app works fine, even individual modules but whenever I try to test everything using nose I get:

`ImportError: No module named simplejson`

I'm using OS X 10.9.5, I get error when installing via `pip` and also when installing from source.

`Running setup.py install for simplejson
    building 'simplejson._speedups' extension
    cc -fno-strict-aliasing -fno-common -dynamic -arch x86_64 -arch i386 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch x86_64 -arch i386 -pipe -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c simplejson/_speedups.c -o build/temp.macosx-10.9-intel-2.7/simplejson/_speedups.o
    simplejson/_speedups.c:2640:42: warning: implicit conversion loses integer precision: 'long' to 'int' [-Wshorten-64-to-32]
            int int_as_string_bitcount_val = PyLong_AsLong(int_as_string_bitcount);
                ~~~~~~~~~~~~~~~~~~~~~~~~~~   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 warning generated.
    cc -bundle -undefined dynamic_lookup -arch x86_64 -arch i386 -Wl,-F. build/temp.macosx-10.9-intel-2.7/simplejson/_speedups.o -o build/lib.macosx-10.9-intel-2.7/simplejson/_speedups.so`

Looks like there is no issue on Fedore 21 VM, even when installing from `pip`.

**Comment by etrepum** [comment]
That's a warning, not an error. If there's an error, you didn't include it in your report. I think the error is likely to be related to how you are running nose, and not related to simplejson or this warning.

**Comment by comatory** [comment]
OK thanks. Still learning to use Github properly.
