### ISSUE TITLE
Cant JSON serialize sqlalchemy.util.langhelpers.symbol

### ISSUE THREAD

**Issue by kshep** [simplejson/simplejson#118]
I've also logged this as a SQLAlchemy issue here: https://bitbucket.org/zzzeek/sqlalchemy/issue/3422/cant-json-serialize

but reporting it here per @zzzeek's comment on that issue.

---

Starting with version SQLAlchemy 0.9.0, simplejson sees util.symbol objects as integers, causing it to generate invalid JSON.

We're trying to serialize stack traces and function arguments as JSON, and although we've defined a custom JSONEncoder default() method to handle non-standard data types, we're getting invalid JSON like:

```
...
"args": [
    "<sqlalchemy.orm.attributes.ScalarAttributeImpl object at 0x4966090>",
    "<sqlalchemy.orm.state.InstanceState object at 0x52ca650>",
    "{'_data': {'follower_count': None, 'followers': None, 'following': None, 'locale': u'zh_hans', 'region': None, 'timezone': u'Africa/Cairo', 'utc_offset': Decimal('2.0')}, '_modified': {'locale': u'zh_hans'}, '_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x52ca650>, 'locale': u'zh_hans'}",
    symbol('PASSIVE_OFF')
],
...
```

...because while our custom default() method handles data types simplejson doesn't recognize, it thinks "symbol('PASSIVE_OFF')" is an int, and dumps the raw value into the JSON.

To reproduce (using python 2.7.6, sqlalchemy 1.0.4, simplejson 3.6.5):

```
Python 2.7.6 (default, Sep  9 2014, 15:04:36)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlalchemy as sa
>>> import json
>>> sym = sa.util.symbol("PASSIVE_OFF")
>>> data = ['str1', 123, sym]
>>> print json.JSONEncoder().encode(data)
["str1", 123, symbol('PASSIVE_OFF')]
>>> print sym
symbol('PASSIVE_OFF')
>>> type(sym)
<class 'sqlalchemy.util.langhelpers.symbol'>
>>> isinstance(sym,int)
True
```

Python 3 handles this slightly differently: rather than "symbol('PASSIVE_OFF')" in the JSON, we see integers like -4343837943729882877 in the output of encode().

**Comment by etrepum** [comment]
This is definitely something that we can work around in simplejson. It was designed mostly with a "consenting adults" sort of policy, but I can certainly see a use case for subclassing number types and providing an alternate repr. That said, many people use the stdlib json library and older versions of simplejson so it might be better to take an alternative approach either in SQLAlchemy or in the application that you're serializing these instances with.

**Comment by etrepum** [comment]
Release v3.7.0 with a workaround for this.

**Comment by kshep** [comment]
Thanks for the quick turnaround, @etrepum.

FWIW, I just noticed that ```float('Inf')``` similarly gets encoded as a bare "Infinity".

**Comment by etrepum** [comment]
That's expected behavior with `allow_nan=True` (the default).

**Comment by etrepum** [comment]
http://simplejson.readthedocs.org/en/latest/#simplejson.dump

**Comment by kshep** [comment]
Aha. Got it. Thanks again!

**Comment by zzzeek** [comment]
cool, and it's in C so we don't have to handwring *too* much about performance.   

@etrepum  - rationale for ints that are repr'ed is that these are objects that both act as a constant "Symbol" which you can compare using "is", e.g. `if sym is PASSIVE_OFF`, but in 0.9 they also became bit-flagged so that we can test the symbols for specific properties and also mutate them into new combinations w/ very low latency using bitwise operations.     The symbols are ideally totally within SQLA internals and not part of normal API or any state you'd see in your data; the use case here that they need to JSON-serialize entire stack frames IMO is a lot more odd than an int subclass with a repr().

**Comment by etrepum** [comment]
Yeah, JSON serializing stack frames is a bit weird. I think this workaround is probably the right call either way, since it's easy enough to produce invalid JSON by accident.

**Comment by hannosch** [comment]
As a reference, this same issue came up in core Python, once IntEnum's got introduced. Bug was http://bugs.python.org/issue18264, fix looks very similar at https://hg.python.org/cpython/rev/ae1a7c420f08
