### ISSUE TITLE
wheels for simplejson

### ISSUE THREAD

**Issue by srkunze** [simplejson/simplejson#122]
Could you provide wheels for simplejson?

http://pythonwheels.com/

**Comment by etrepum** [comment]
It's not easy to do given platform specific extensions. If someone makes it easier (some sort of cross platform build farm service) then I'd be happy to.

**Comment by edmorley** [comment]
Wheels can be built for linux and OS X on Travis CI automatically:
http://docs.travis-ci.com/user/deployment/pypi/
https://github.com/MacPython/wiki/wiki/Wheel-building

There's also a guide for using appveyor to build the windows wheels:
http://python-packaging-user-guide.readthedocs.org/en/latest/appveyor/

Does that help? :-)

**Comment by edmorley** [comment]
Also, if there isn't a wheel package for a specific platform, does that matter? It will just fallback to the standard archive.

**Comment by jarondl** [comment]
For future reference, #130 creates wheels for windows. (although they are not on PyPI yet)

**Comment by Ivoz** [comment]
@edmorley linux binary packages are currently not allowed on PyPI. Windows and OS X wheels could be uploaded, though.

**Comment by etrepum** [comment]
Not sure if anyone noticed, but thanks to all of the help here simplejson now has wheels for Mac & Windows.

**Comment by srkunze** [comment]
Nice! :) Thanks.

**Comment by aebrahim** [comment]
Glad I could be of help, and thanks for all your work on simplejson!

Actually, wheels can now be built for linux as well! Check out [PEP 513](https://www.python.org/dev/peps/pep-0513/) and the very helpful stuff from the
[manylinux](https://github.com/pypa/manylinux) project for more information.

These two scripts will build the manylinux wheels for you. If you have docker installed, place them in the same empty folder and run the ```run_simplejson.sh``` script.

Call this file ```build_simplejson.sh```
```shell
#!/bin/bash

for PYBIN in /opt/python/*/bin; do
    ${PYBIN}/pip wheel simplejson
done

# Bundle external shared libraries into the wheels
for whl in *.whl; do
    auditwheel repair $whl -w /io/wheelhouse/
done
```

Call this file ```build_simplejson.sh```
```shell
export DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
docker run --rm -v `pwd`:/io $DOCKER_IMAGE /io/build_libsbml.sh
export DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
docker run --rm -v `pwd`:/io $DOCKER_IMAGE /io/build_libsbml.sh
```

**Comment by etrepum** [comment]
If you'd like to see wheels for simplejson, I'd be happy to review and accept a PR that sets this up with freely available CI infrastructure (e.g. Travis, which is what is used for OS X wheels)
