### ISSUE TITLE
simplejson generates invalid json with iterable_as_array and indent is set

### ISSUE THREAD

**Issue by ffix** [simplejson/simplejson#128]
I've found a strange issue with iterable_as_array=True, indent=any_integer_value and empty iterable.

It's easy to reproduce:
```
In [1]: from simplejson import dumps

In [2]: x=(i for i in [])

In [3]: dumps(x, iterable_as_array=True, indent=2)
Out[3]: '\n]'
```
Yes, it's newline and right square bracket.

There is no issue without indent option:
```
In [6]: dumps(x, iterable_as_array=True)
Out[6]: '[]'
```

I'm using latest version of simplejson (3.8.0) with python 3.5.

**Comment by etrepum** [comment]
Thank you for the report, embarrassingly the test suite wasn't running and didn't cover this case so this was able to slip through.
