### ISSUE TITLE
error __init__() got an unexpected keyword argument 'iterable_as_array'

### ISSUE THREAD

**Issue by Six-wars** [simplejson/simplejson#129]
I've upgraded all the django apps and on my website and djangorestframework which serves data to a mobile app crashed. The issue seems to end at simplejson http://stackoverflow.com/questions/33562605/django-rest-framework-simplejson-error-init-got-an-unexpected-keyword-argu

**Comment by etrepum** [comment]
What version of django and djangorestframework are you using? The bug is definitely in there, not simplejson, but I can help you track it down.

**Comment by etrepum** [comment]
The symptom looks like something is subclassing JSONEncoder, but not passing through *args and **kwargs in the __init__

**Comment by Six-wars** [comment]
It's Django 1.5.5 and djangorestframework==0.4.0

**Comment by etrepum** [comment]
Looks like this is a bug in that version of Django, you'll have to update it.
