### ISSUE TITLE
Signed floats without zero before decimal point not decoded

### ISSUE THREAD

**Issue by JorjMcKie** [simplejson/simplejson#131]
A valid float-convertible Python string will not be decoded correctly if the sign is immediately followed by decimal point:

    C:\>python
    Python 2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)] on win32
    Type "help", "copyright", "credits" or "license" for more information.
    >>> a='-.123'
    >>> float(a)
    -0.123

**But:**

    >>> import simplejson
    >>> simplejson.loads(a)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "C:\Python27\lib\site-packages\simplejson\__init__.py", line 516, in loads
        return _default_decoder.decode(s)
      File "C:\Python27\lib\site-packages\simplejson\decoder.py", line 370, in decode
        obj, end = self.raw_decode(s)
      File "C:\Python27\lib\site-packages\simplejson\decoder.py", line 400, in raw_decode
        return self.scan_once(s, idx=_w(s, idx).end())
    simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 2 (char 1)
    >>>

**Comment by etrepum** [comment]
Not a bug, numbers in the JSON specification must have a number before the decimal. The JSON specification is not based on what Python will or won't decode on its own. Here's the relevant section of [RFC 7159](https://tools.ietf.org/html/rfc7159):

```
   Numeric values that cannot be represented in the grammar below (such
   as Infinity and NaN) are not permitted.

      number = [ minus ] int [ frac ] [ exp ]

      decimal-point = %x2E       ; .

      digit1-9 = %x31-39         ; 1-9

      e = %x65 / %x45            ; e E

      exp = e [ minus / plus ] 1*DIGIT

      frac = decimal-point 1*DIGIT

      int = zero / ( digit1-9 *DIGIT )

      minus = %x2D               ; -

      plus = %x2B                ; +

      zero = %x30                ; 0
```

**Comment by JorjMcKie** [comment]
ok, understood.
thanks for the prompt reaction.
