### ISSUE TITLE
Make JSON number serialization compatible with ES6 (and V8)

### ISSUE THREAD

**Issue by cyberphone** [simplejson/simplejson#133]
http://bugs.python.org/issue26229

**Comment by etrepum** [comment]
This isn't going to be implemented by me, implementing exactly V8's number formatting is not within the scope of simplejson nor is it part of the JSON spec. If some signed JSON spec requires anything more than mathematical identity then it's a bad spec that's not well designed for interoperability.

**Comment by cyberphone** [comment]
@etrepum The signature scheme runs in "node.js" and in all major browsers except MSFT's.

These are the two alternatives:

JSON Cleartext Signature (JCS): https://cyberphone.github.io/openkeystore/resources/docs/jcs.html#ECMAScript_Compatibility_Mode

```javascript
var signedObject = {
      // The data
      statement: "Hello signed world!",
      otherProperties: [2000, true],
      // The signature
      signature: {
          algorithm: "ES256",
          publicKey: {
              type: "EC",
              curve: "P-256",
              x: "vlYxD4dtFJOp1_8_QUcieWCW-4KrLMmFL2rpkY1bQDs",
              y: "fxEF70yJenP3SPHM9hv-EnvhG6nXr3_S-fDqoj-F6yM"
          },
          value: "2H__TkcV28QpGWPkyVbR1CW0I8L4xA...CTyYfmAippJXqdzgNAonnFPVCSI5A6novMQ"
      }
};
```


JSON Web Signature (JWS): https://tools.ietf.org/rfc/rfc7515.txt

```javascript
var signedObject = {
      payload: "eyJpc3MiOiJqb2UiLA0KICJleHAiOjEz...eGFtcGxlLmNvbS9pc19yb290Ijp0cnVlfQ",
      protected: "eyJhbGciOiJFUzI1NiJ9",
      signature: "DtEhU3ljbEg8L38VWAfUAqOyKA...gfTjDxw5djxLa8IS lSApmWQxfKTUJqPP3-Kg6NU1Q"
};
```

**Comment by etrepum** [comment]
If there was a library available with exactly the V8 algorithm to format floats then we could add an option here to use it, but implementing such a thing is not within the scope of this project (especially considering that it would also require a pure Python implementation of that algorithm).

**Comment by cyberphone** [comment]
Right.  It should be a part of the interpreter

**Comment by cyberphone** [comment]
Works like a charm with 3.5.1

##################################################################
# Convert a Python double/float into an ES6/V8 compatible string #
##################################################################
def convert2Es6Format(value):
# Convert double/float to str using the native Python formatter
    pyDouble = str(value)
    pySign = ''
    if pyDouble.find('-') == 0:
#
#     Save sign separately, it doesn't have any role in the rest
#
        pySign = '-'
        pyDouble = pyDouble[1:]
    pyExpStr = ''
    pyExpVal = 0
    q = pyDouble.find('e')
    if q > 0:
#
# Grab the exponent and remove it from the number
#
        pyExpStr = pyDouble[q:]
        if pyExpStr[2:3] == '0':
#
# Supress leading zero on exponents
#
            pyExpStr = pyExpStr[0:2] + pyExpStr[3:]
        pyDouble = pyDouble[0:q]
        pyExpVal = int(pyExpStr[1:])
#
# Split number in pyFirst + pyDot + pyLast
#
    pyFirst = pyDouble
    pyDot = ''
    pyLast = ''
    q = pyDouble.find('.')
    if q > 0:
        pyDot = '.'
        pyFirst = pyDouble[0:q]
        pyLast = pyDouble[q + 1:]
#
# Now the string is split into: pySign + pyFirst + pyDot + pyLast + pyExpStr
#
    if pyLast == '0':
#
# Always remove trailing .0
#
        pyDot = ''
        pyLast = ''
    if pyExpVal > 0 and pyExpVal < 21:
#
# Integers are shown as is with up to 21 digits
#
        pyFirst += pyLast
        pyLast = ''
        pyDot = ''
        pyExpStr = ''
        q = pyExpVal - len(pyFirst)
        while q >= 0:
            q -= 1;
            pyFirst += '0'
    elif pyExpVal < 0 and pyExpVal > -7:
#
# Small numbers are shown as 0.etc with e-6 as lower limit
#
        pyLast = pyFirst + pyLast
        pyFirst = '0'
        pyDot = '.'
        pyExpStr = ''
        q = pyExpVal
        while q < -1:
            q += 1;
            pyLast = '0' + pyLast
#
# The resulting sub-strings are concatenated
#
    return pySign + pyFirst + pyDot + pyLast + pyExpStr

**Comment by etrepum** [comment]
Do you have a proof and/or extensive test suite that demonstrates the mathematical equivalence between this representation and the original representation?

**Comment by cyberphone** [comment]
I do not have any mathematical proof but here is 10 million value test file:
http://webpki.org/ietf/es6testfile.txt

```python
import binascii
import struct

#
# Test program using a 100 million value file formatted as follows:
# value in ieee hex representation (1-15 digits) + ',' + correct ES6 format + '\n'
#
f = open('c:\\es6\\numbers\\es6testfile100m.txt','rb')
l = 0;
string = '';
while True:
    byte = f.read(1);
    if len(byte) == 0:
        exit(0)
    if byte == b'\n':
        l = l + 1;
        i = string.find(',')
        if i <= 0 or i >= len(string) - 1:
            print('Bad string: ' + str(i))
            exit(0)
        hex = string[:i]
        while len(hex) < 16:
            hex = '0' + hex
        value = struct.unpack('>d',binascii.a2b_hex(hex))[0]
        es6Format = string[i + 1:]
        pyFormat = convert2Es6Format(value)
        if pyFormat != es6Format or value != float(pyFormat) or repr(value) != str(value):
            print('IEEE:   ' + hex + '\nPython: ' + str(value) + '\nES6/V8: ' + es6Format)
            exit(0)
        string = ''
        if l % 10000 == 0:
            print(l)
    else:
        string += byte.decode(encoding='UTF-8')
```
