### ISSUE TITLE
Deserialze list ios

### ISSUE THREAD

**Issue by amccorma** [simplejson/simplejson#136]
iOS xamarin C#

Will not deseralize a list of objects. I traced the code in the debugger to the point where it assigns the list to the property.  Setter.value.value ()  the objects are correct but returns a null list.

**Comment by amccorma** [comment]
Android had not problem deserializing this class.  iOS no luck.

```
public class TakeAction
	{
		public TakeAction()
		{
		}

		/// <summary>
		/// collection of items
		/// </summary>
		public List<TakeActionItem> Items
	}
```

Notice the property Items.  Not really a property.  But worked ok on Android.

If I change, **Items** to a property, works.

```
public class TakeAction
	{
		public TakeAction()
		{
		}

		/// <summary>
		/// collection of items
		/// </summary>
		public List<TakeActionItem> Items { get; set; }
	}

```

Should have been a property.  fixed.

**Comment by etrepum** [comment]
I think you have found the wrong GitHub project. simplejson is a library for Python.
