### ISSUE TITLE
Simplejson what version do i need for zgemma

### ISSUE THREAD

**Issue by Zgerman** [simplejson/simplejson#140]
hHi i got a zgemma box with vix image i want to install simplejson what file do i need as there are so many thank you

File	Type	Py Version	Uploaded on	Size
simplejson-3.8.2-cp27-cp27m-macosx_10_9_x86_64.whl (md5, pgp)	Python Wheel	cp27	2016-02-15	65KB
simplejson-3.8.2-cp27-cp27m-win32.whl (md5, pgp)	Python Wheel	cp27	2016-02-15	63KB
simplejson-3.8.2-cp27-cp27m-win_amd64.whl (md5, pgp)	Python Wheel	cp27	2016-02-15	64KB
simplejson-3.8.2-cp33-none-win32.whl (md5, pgp)	Python Wheel	cp33	2016-02-15	62KB
simplejson-3.8.2-cp33-none-win_amd64.whl (md5, pgp)	Python Wheel	cp33	2016-02-15	63KB
simplejson-3.8.2-cp34-cp34m-win32.whl (md5, pgp)	Python Wheel	cp34	2016-02-15	62KB
simplejson-3.8.2-cp34-cp34m-win_amd64.whl (md5, pgp)	Python Wheel	cp34	2016-02-15	63KB
simplejson-3.8.2-cp35-cp35m-macosx_10_9_x86_64.whl (md5, pgp)	Python Wheel	cp35	2016-02-15	65KB
simplejson-3.8.2-cp35-cp35m-win32.whl (md5, pgp)	Python Wheel	cp35	2016-02-15	63KB
simplejson-3.8.2-cp35-cp35m-win_amd64.whl (md5, pgp)	Python Wheel	cp35	2016-02-15	65KB
simplejson-3.8.2.tar.gz (md5, pgp)	Source		2016-02-15	74KB
simplejson-3.8.2.win-amd64-py2.7.exe (md5, pgp)	MS Windows installer	2.7	2016-02-15	282KB
simplejson-3.8.2.win-amd64-py3.3.exe (md5, pgp)	MS Windows installer	3.3	2016-02-15	279KB
simplejson-3.8.2.win-amd64-py3.4.exe (md5, pgp)	MS Windows installer	3.4	2016-02-15	279KB
simplejson-3.8.2.win-amd64-py3.5.exe (md5, pgp)	MS Windows installer	3.5	2016-02-15	198KB
simplejson-3.8.2.win32-py2.7.exe (md5, pgp)	MS Windows installer	2.7	2016-02-15	254KB
simplejson-3.8.2.win32-py3.3.exe (md5, pgp)	MS Windows installer	3.3	2016-02-15	248KB
simplejson-3.8.2.win32-py3.4.exe (md5, pgp)	MS Windows installer	3.4	2016-02-15	248KB
simplejson-3.8.2.win32-py3.5.exe (md5, pgp)	MS Windows installer	3.5	2016-02-15	189KB

**Comment by etrepum** [comment]
I don't have any idea, never heard of zgemma or vix. Generally speaking you should be installing it with a tool such as pip, not by manually downloading a file.
