### ISSUE TITLE
 getting memory error while trying to do dumps even for a very small data

### ISSUE THREAD

**Issue by vivekhas3** [simplejson/simplejson#145]
client_data_extension_req = simplejson.dumps(client_data_extension_req)
  File "/usr/local/lib/python2.7/site-packages/simplejson/__init__.py", line 380, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python2.7/site-packages/simplejson/encoder.py", line 269, in encode
    return encode_basestring_ascii(o)
MemoryError

**Comment by etrepum** [comment]
Can't really help you without more information. What exactly is `client_data_extension_req`? What version of simplejson and Python are you using?

**Comment by vivekhas3** [comment]
Its a simple data structure:

` [
    {
        "keys": {
            "Subscriber Key": ""
        },
        "values": {
            "MobileNumber": "",

        }
    }
]`

simplejson version is 3.8.2

Python vesion is 2.7.10

**Comment by etrepum** [comment]
That's syntactically invalid JSON. Could you post a standalone code sample that reproduces this issue?
