### ISSUE TITLE
Don't publish os x tarball as source code

### ISSUE THREAD

**Issue by skeenan947** [simplejson/simplejson#147]
With 3.9.0, pip is pulling down simplejson-3.9.0.macosx-10.10-x86_64.tar.gz instead of the actual source, which causes the install to fail.

**Comment by skeenan947** [comment]
Also, if you can remove simplejson-3.9.0.macosx-10.10-x86_64.tar.gz from pypi so pip doesn't try to download and install it, that would be immensely helpful.

**Comment by etrepum** [comment]
Well that's silly that it marked that as source. Deleted.

**Comment by skeenan947** [comment]
thanks! :)
