### ISSUE TITLE
Where to find the c_make_encoder code?

### ISSUE THREAD

**Issue by zhangqunshi** [simplejson/simplejson#150]
Hi guys,

I want to add a init parameter 'emptystr' for JSONEncoder, the purpose of the parameter is to convert the None to empty string, not the 'null'. But i cannot find code of 'c_make_encoder' 
```
try:
    from _json import make_encoder as c_make_encoder
except ImportError:
    c_make_encoder = None
```
Anybody knows where is the C code?

Thanks,
Kris

**Comment by etrepum** [comment]
https://github.com/simplejson/simplejson/blob/master/simplejson/_speedups.c#L2598-L2736

**Comment by zhangqunshi** [comment]
thanks etrepum.
