### ISSUE TITLE
Type annotations

### ISSUE THREAD

**Issue by vidstige** [simplejson/simplejson#155]
To get a better developer experience, let's add python3 type annotations

```python3
def loads(s: str) -> dict:
  return dict()
```

This will allow tools such as IDEas and linters to work better.

**Comment by etrepum** [comment]
PRs accepted, would be a nice way to start contributing. I don't think inline annotations like that will work given the Python 2 compatibility requirements, but surely there is a way to provide annotations in a separate file or something like that.

**Comment by vidstige** [comment]
I see, what's the best way to go about python3. Do you have some code already that detects python3? Do know what is the best way to detect python3? I was thinking otherwise, just having a simple if-statement in __init__.py could be a solution.

**Comment by etrepum** [comment]
I'm sure that if you find documentation for using type specs in projects that are compatible with Python 2 then they'll describe what to do. I don't think that runtime detection will help much for this.

**Comment by vidstige** [comment]
After further investigation something called "stub files" are the preferred way of doing this according to [PEP 484](https://www.python.org/dev/peps/pep-0484/#stub-files).

**Comment by etrepum** [comment]
Yep, that looks like the appropriate solution for simplejson.

**Comment by vidstige** [comment]
It turned out there already _is_ type stubs for simplejson provided by the typeshed project, see them [here](https://github.com/python/typeshed/blob/master/stdlib/3/json.pyi#L34). 

The problem we had was we has lot of code that goes like this

```python3
x = json.loads('{"x": 17}')  # type: dict
x.update({"y": 49})
```

Without the `# type` hint, we would get linter warnings with "unknown type" in python3. However, the problem is not that json lacks type annotations, but that the `loads` function is truly dynamically typed, the solution is to do something like this

```
def parse_json(s: str) -> dict:
    d = json.loads(s)  # type: dict
    assert isinstance(d, dict)
    return d
```
