### ISSUE TITLE
Typo in the doc for loads

### ISSUE THREAD

**Issue by bmampaey** [simplejson/simplejson#161]
The function loads take a string s as first parameter, but the doc says that it takes fp

function:: load**s(fp**, encoding='utf-8', cls=None, object_hook=None, \
                    parse_float=None, parse_int=None, \
                    parse_constant=None, object_pairs_hook=None, \
                    use_decimal=None, **kw)

   Deserialize *s* (a :class:`str` or :class:`unicode` instance containing a JSON
   document) to a Python object. :exc:`JSONDecodeError` will be
   raised if the given JSON document is not valid.

**Comment by serhiy-storchaka** [comment]
Thank you for your report @bmampaey.
