### ISSUE TITLE
item_sort_key always uses itemgetter in 3.11

### ISSUE THREAD

**Issue by doozr** [simplejson/simplejson#173]
Got a strange bug when upgrading 3.10.0 to 3.11.0 via pip.

A test started failing that used a custom sort function via `item_sort_key`. It seems that setting this kwarg has the effect of enabling sorting using the default `itemgetter` in 3.11.0.

This occurs when using the C encoder implementation.

Python is 2.7.11 on Ubuntu 16.04.

Using this code:

    import simplejson

    def sortit(x):
      return x[1]

    a = {
      "c": "3",
      "b": "1",
      "a": "2"
    }

    print simplejson.dumps(a, item_sort_key=sortit)

On 3.10.0:

    $ python test.py
    {"b": "1", "c": "2", "a": "3"}

And on 3.11.0:

    $ python test.py
    {"a": "2", "b": "1", "c": "3"}

**Comment by felixonmars** [comment]
Same here. The related tests are also failing when the C extension is present:

```
======================================================================== FAILURES =========================================================================
________________________________________________________________ TestItemSortKey.test_case ________________________________________________________________

self = <simplejson.tests.test_item_sort_key.TestItemSortKey testMethod=test_case>

    def test_case(self):
        a = {'a': 1, 'c': 5, 'Jack': 'jill', 'pick': 'axe', 'Array': [1, 5, 6, 9], 'tuple': (83, 12, 3), 'crate': 'dog', 'zeak': 'oh'}
        self.assertEqual(
            '{"Array": [1, 5, 6, 9], "Jack": "jill", "a": 1, "c": 5, "crate": "dog", "pick": "axe", "tuple": [83, 12, 3], "zeak": "oh"}',
            json.dumps(a, item_sort_key=itemgetter(0)))
        self.assertEqual(
            '{"a": 1, "Array": [1, 5, 6, 9], "c": 5, "crate": "dog", "Jack": "jill", "pick": "axe", "tuple": [83, 12, 3], "zeak": "oh"}',
>           json.dumps(a, item_sort_key=lambda kv: kv[0].lower()))
E       AssertionError: '{"a": 1, "Array": [1, 5, 6, 9], "c": 5, "cr[75 chars]oh"}' != '{"Array": [1, 5, 6, 9], "Jack": "jill", "a"[75 chars]oh"}'
E       - {"a": 1, "Array": [1, 5, 6, 9], "c": 5, "crate": "dog", "Jack": "jill", "pick": "axe", "tuple": [83, 12, 3], "zeak": "oh"}
E       ?  --------                                              ----------------
E       + {"Array": [1, 5, 6, 9], "Jack": "jill", "a": 1, "c": 5, "crate": "dog", "pick": "axe", "tuple": [83, 12, 3], "zeak": "oh"}
E       ?                        ++++++++++++++++++++++++

simplejson/tests/test_item_sort_key.py:20: AssertionError
____________________________________________________________ TestItemSortKey.test_simple_first ____________________________________________________________

self = <simplejson.tests.test_item_sort_key.TestItemSortKey testMethod=test_simple_first>

    def test_simple_first(self):
        a = {'a': 1, 'c': 5, 'jack': 'jill', 'pick': 'axe', 'array': [1, 5, 6, 9], 'tuple': (83, 12, 3), 'crate': 'dog', 'zeak': 'oh'}
        self.assertEqual(
            '{"a": 1, "c": 5, "crate": "dog", "jack": "jill", "pick": "axe", "zeak": "oh", "array": [1, 5, 6, 9], "tuple": [83, 12, 3]}',
>           json.dumps(a, item_sort_key=json.simple_first))
E       AssertionError: '{"a": 1, "c": 5, "crate": "dog", "jack": "jill", "p[67 chars] 3]}' != '{"a": 1, "array": [1, 5, 6, 9], "c": 5, "crate": "d[67 chars]oh"}'
E       - {"a": 1, "c": 5, "crate": "dog", "jack": "jill", "pick": "axe", "zeak": "oh", "array": [1, 5, 6, 9], "tuple": [83, 12, 3]}
E       + {"a": 1, "array": [1, 5, 6, 9], "c": 5, "crate": "dog", "jack": "jill", "pick": "axe", "tuple": [83, 12, 3], "zeak": "oh"}

simplejson/tests/test_item_sort_key.py:11: AssertionError
========================================================== 2 failed, 128 passed in 1.01 seconds ===========================================================
```

**Comment by etrepum** [comment]
Is this with a clean build of simplejson? None of this is reproducible here or in travis. This kind of problem could happen if you have one version of _speedups.so and another of simplejson.

**Comment by felixonmars** [comment]
Travis has six skips "ssssss" which I think is the speedup tests, so I think speedup isn't working correctly in Travis.

Also looking into the code: https://github.com/simplejson/simplejson/blob/de28cced9a9a5ff1a7a93eb52bd2a52a01d0476a/simplejson/_speedups.c#L2677

It seems to be overriding item_sort_key to itemgetter0 unconditionally.

**Comment by etrepum** [comment]
It's normal for five tests to be reported as skipped even when the extensions are present because the test suite runs twice, once with extensions on and once with it off. Which build are you seeing six skips on?

If you follow the context, `item_sort_key` is unconditionally `itemgetter0` when `item_sort_key != Py_None` and `PyObject_IsTrue(sort_keys)` which is not the case in your example.

**Comment by felixonmars** [comment]
I see those skips on all 8 travis envs, and there's no case without those skips. Also in the run.sh script there's only one "setup.py test" after building the extensions.

**Comment by etrepum** [comment]
All test runs should have 5 skips. Where do you see six? Could you provide a URL to where you see six skips?

Here's an example: https://travis-ci.org/simplejson/simplejson/jobs/244225647

```
running test
.......................................................................................................................................................................................................sssss........................................................
----------------------------------------------------------------------
Ran 260 tests in 1.486s
OK (skipped=5)
```

If speedups were not present, there would be six skips instead of five.

**Comment by felixonmars** [comment]
Here it is: https://travis-ci.org/simplejson/simplejson/jobs/244225651#L340

**Comment by etrepum** [comment]
Python 3 should have six skips, there's an additional test that runs.

```
    if PY3:
        @skip_if_speedups_missing
        def test_bad_encoding(self):
            with self.assertRaises(UnicodeEncodeError):
                encoder.JSONEncoder(encoding='\udcff').encode({b('key'): 123})
```

**Comment by etrepum** [comment]
(I was looking at Python 2 since that's the version that was reported in this issue, sorry for the confusion)

**Comment by felixonmars** [comment]
Yes, but these are all skipped because of missing speedups. This should not be skipped if we intended to run the tests with the speedups.

**Comment by etrepum** [comment]
Like I said [before](https://github.com/simplejson/simplejson/issues/173#issuecomment-309504750): the test suite runs twice, once with the speedups enabled, and once with the speedups disabled. These skips are expected even when the extension is built and available.

```
    import simplejson
    if simplejson._import_c_make_encoder() is None:
        suite.addTest(TestMissingSpeedups())
    else:
        suite = unittest.TestSuite([
            suite,
            NoExtensionTestSuite([get_suite()]),
        ])
```

**Comment by felixonmars** [comment]
Ah, I missed that part of code, sorry...

The test in #174 is how I reproduced the problem. Any hint why it behaves differently?

**Comment by etrepum** [comment]
Probably some sort of issue with module loading (e.g. sys.path precedence) where you're pulling in the extension from a different version of simplejson (e.g. installed elsewhere) than the python code and test suite.

**Comment by felixonmars** [comment]
That's unlikely, because I am also building in a clean chroot with only the version of simplejson to be tested. In the build log of Travis you can also see that speedups were built right before the tests were run.

This is what I get in a clean environment with only this version of simplejson installed:

```
>>> import simplejson as json
>>> a = {'a': 1, 'c': 5, 'Jack': 'jill', 'pick': 'axe', 'Array': [1, 5, 6, 9], 'tuple': (83, 12, 3), 'crate': 'dog', 'zeak': 'oh'}
>>> json.dumps(a, item_sort_key=lambda kv: kv[0].lower())
'{"Array": [1, 5, 6, 9], "Jack": "jill", "a": 1, "c": 5, "crate": "dog", "pick": "axe", "tuple": [83, 12, 3], "zeak": "oh"}'
>>> json._toggle_speedups(False)
>>> json.dumps(a, item_sort_key=lambda kv: kv[0].lower())
'{"a": 1, "Array": [1, 5, 6, 9], "c": 5, "crate": "dog", "Jack": "jill", "pick": "axe", "tuple": [83, 12, 3], "zeak": "oh"}'
```

**Comment by felixonmars** [comment]
Also it is strange that setting sort_keys to either value doesn't change the behavior:

```
>>> json.dumps(a, item_sort_key=lambda kv: kv[0].lower(), sort_keys=False)
'{"Array": [1, 5, 6, 9], "Jack": "jill", "a": 1, "c": 5, "crate": "dog", "pick": "axe", "tuple": [83, 12, 3], "zeak": "oh"}'
>>> json.dumps(a, item_sort_key=lambda kv: kv[0].lower(), sort_keys=0)
'{"Array": [1, 5, 6, 9], "Jack": "jill", "a": 1, "c": 5, "crate": "dog", "pick": "axe", "tuple": [83, 12, 3], "zeak": "oh"}'
>>> json.dumps(a, item_sort_key=lambda kv: kv[0].lower(), sort_keys=True)
'{"Array": [1, 5, 6, 9], "Jack": "jill", "a": 1, "c": 5, "crate": "dog", "pick": "axe", "tuple": [83, 12, 3], "zeak": "oh"}'
>>> json._toggle_speedups(False)
>>> json.dumps(a, item_sort_key=lambda kv: kv[0].lower(), sort_keys=True)
'{"a": 1, "Array": [1, 5, 6, 9], "c": 5, "crate": "dog", "Jack": "jill", "pick": "axe", "tuple": [83, 12, 3], "zeak": "oh"}'
>>> json.dumps(a, item_sort_key=lambda kv: kv[0].lower())
'{"a": 1, "Array": [1, 5, 6, 9], "c": 5, "crate": "dog", "Jack": "jill", "pick": "axe", "tuple": [83, 12, 3], "zeak": "oh"}'
>>> json.dumps(a, item_sort_key=lambda kv: kv[0].lower(), sort_keys=False)
'{"a": 1, "Array": [1, 5, 6, 9], "c": 5, "crate": "dog", "Jack": "jill", "pick": "axe", "tuple": [83, 12, 3], "zeak": "oh"}'
```

**Comment by doozr** [comment]
This is a transcript of my testing:

$ git clone https://github.com/simplejson/simplejson.git
Cloning into 'simplejson'...
remote: Counting objects: 2861, done.
remote: Total 2861 (delta 0), reused 0 (delta 0), pack-reused 2861
Receiving objects: 100% (2861/2861), 1.09 MiB | 362.00 KiB/s, done.
Resolving deltas: 100% (1831/1831), done.
Checking connectivity... done.
$ cd simplejson/
$ python --version
Python 2.7.12
$ virtualenv /tmp/simplejson
New python executable in /tmp/simplejson/bin/python
Installing setuptools, pip, wheel...done.
$ . /tmp/simplejson/bin/activate
(simplejson) $ python --version
Python 2.7.12
(simplejson) $ pip install -e .
Obtaining file:///home/craig/src/github.com/simplejson/simplejson
Installing collected packages: simplejson
  Found existing installation: simplejson 3.11.0
    Not uninstalling simplejson at /home/craig/src/github.com/simplejson/simplejson, outside environment /tmp/simplejson
  Running setup.py develop for simplejson
Successfully installed simplejson
(simplejson) $ nosetests simplejson
S...........................................................................FF.................................................
======================================================================
FAIL: test_case (simplejson.tests.test_item_sort_key.TestItemSortKey)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/craig/src/github.com/simplejson/simplejson/simplejson/tests/test_item_sort_key.py", line 20, in test_case
    json.dumps(a, item_sort_key=lambda kv: kv[0].lower()))
AssertionError: '{"a": 1, "Array": [1, 5, 6, 9], "c": 5, "crate": "dog", "Jack": "jill", "pick": "axe", "tuple": [83, 12, 3], "zeak": "oh"}' != '{"Array": [1, 5, 6, 9], "Jack": "jill", "a": 1, "c": 5, "crate": "dog", "pick": "axe", "tuple": [83, 12, 3], "zeak": "oh"}'

======================================================================
FAIL: test_simple_first (simplejson.tests.test_item_sort_key.TestItemSortKey)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/craig/src/github.com/simplejson/simplejson/simplejson/tests/test_item_sort_key.py", line 11, in test_simple_first
    json.dumps(a, item_sort_key=json.simple_first))
AssertionError: '{"a": 1, "c": 5, "crate": "dog", "jack": "jill", "pick": "axe", "zeak": "oh", "array": [1, 5, 6, 9], "tuple": [83, 12, 3]}' != '{"a": 1, "array": [1, 5, 6, 9], "c": 5, "crate": "dog", "jack": "jill", "pick": "axe", "tuple": [83, 12, 3], "zeak": "oh"}'

----------------------------------------------------------------------
Ran 127 tests in 0.381s

FAILED (SKIP=1, failures=2)
(simplejson) $

**Comment by felixonmars** [comment]
I think I found why Travis is passing - that very test was never added to tests/__init__.py, so it wasn't tested on Travis. The tools we use (nose/pytest) are using auto discovery and will run this missing test.

**Comment by etrepum** [comment]
Yeah, I had just discovered the same, thanks, will fix shortly and post a new version. In the meantime I've removed this version from pypi.
