### ISSUE TITLE
Upload 3.11.0 to PyPI

### ISSUE THREAD

**Issue by jberends** [simplejson/simplejson#177]
Trough pyup I received an upgrade notice for simplejson to 3.11, however pip isntall fails as 3.11 is not uploaded to PyPI.

PyPI: https://pypi.python.org/pypi/simplejson/3.11.0 --> 404

**Comment by azaghal** [comment]
Just ran into this myself during updates check, and got a bit paranoid :)

I think the version was pulled on purpose due to a bug, see:

https://github.com/simplejson/simplejson/issues/173#issuecomment-309519753

**Comment by jberends** [comment]
we'll wait for 3.11.1 then and get myself a coffee... (in a good way, we love simplejson)

**Comment by etrepum** [comment]
v3.11.1 is now available
