### ISSUE TITLE
Provide manylinux1 wheel distribution on PyPI 

### ISSUE THREAD

**Issue by edmorley** [simplejson/simplejson#181]
Hi!

This package is already available in wheel form for OS X/Windows, however it would be great to add Linux to that list via the new manylinux1 variant:
https://www.python.org/dev/peps/pep-0513/
https://github.com/pypa/python-manylinux-demo

Many thanks :-)

**Comment by etrepum** [comment]
The best way to make this happen quickly would be to submit a pull request that makes this part of the Travis workflow. Seems like a fine idea though!

**Comment by jmehnle** [comment]
I have an interest in this. I wish I knew how to make the requisite Travis changes, or I'd jump on immediately. Any pointers?

**Comment by etrepum** [comment]
Best thing to do would be to find another project that builds them and see what they do

**Comment by etrepum** [comment]
Per https://github.com/simplejson/simplejson/issues/237#issue-358319014 these wheels do not work on CentOS. Going to roll back linux wheels until we have CI that tests that they can actually be installed.

**Comment by browniebroke** [comment]
Is it still an issue? I would think that it's a solved problem with cibuildwheel...

**Comment by edmorley** [comment]
I see manylinux wheels are published now:
https://pypi.org/project/simplejson/#files

...so this can be closed :-)
