### ISSUE TITLE
Threaded use of simplejson does not work if thread is run during an import

### ISSUE THREAD

**Issue by jus-x** [simplejson/simplejson#184]
To reproduce:

1. Create a file testfile.py:

```
import simplejson
import threading

class worker(threading.Thread):
 def run(self):
  simplejson.dumps({})

w = worker()
w.start()
w.join()

print 'Worker finished'
```

2. Run the file

> $ python test.py
> Worker finished

The output will be as expected

3. Create a file import_testfile.py:
`import testfile`

4. Run import_testfile.py
> $ python import_testfile.py
> 

I've tested the issue for version **3.11.1** and **3.8.1**. The issue does **not** occur for version **3.8.1**

I am running python 2.7.12 on OSX El Capitan.

**Comment by jus-x** [comment]
To reproduce:

1. Create a file testfile.py:

```
import simplejson
import threading

class worker(threading.Thread):
 def run(self):
  simplejson.dumps({})

w = worker()
w.start()
w.join()

print 'Worker finished'
```

2. Run the file

> $ python test.py
> Worker finished

The output will be as expected

3. Create a file import_testfile.py:
`import testfile`

4. Run import_testfile.py
> $ python test.py
> 

The file will run indefinitely

**Comment by etrepum** [comment]
I can't reproduce this, going to need more information about the environment and versions of everything involved.

**Comment by jus-x** [comment]
I've updated the first comment

**Comment by etrepum** [comment]
I can reproduce this, will take a look when I get a chance. If you sort it out or root cause the problem in the meantime, please do send a PR and/or add more information to this issue.

**Comment by etrepum** [comment]
Looks like the regression is in v3.10.0
