### ISSUE TITLE
String enums broke in 3.12.0

### ISSUE THREAD

**Issue by WeirdCarrotMonster** [simplejson/simplejson#185]
```python
from enum import Enum

class A(str, Enum):
    A = "a"
    B = "b"
```

with simplejson 3.11.1

```python
>>> import simplejson
>>> simplejson.dumps(A.A)
'"a"'
```

with simplejson 3.12.0
```python
>>> import simplejson
>>> simplejson.dumps(A.A)
'"A.A"'
```

**Comment by etrepum** [comment]
That’s unusual, nothing changed in that code path. What version of Python is this?

**Comment by WeirdCarrotMonster** [comment]
3.6.3

**Comment by serhiy-storchaka** [comment]
Python implementation calls `str()` on the string subclass instance (and this can invoce the custom `__str__` method), C implementation uses the string content directly.
```python
       if type(s) is not text_type:
            s = text_type(s)
```
The `json` module is not affected.

**Comment by WeirdCarrotMonster** [comment]
I've created a test case: https://github.com/WeirdCarrotMonster/simplejson-enum-test.git

@felixonmars There is no problem with archlinux package indeed. Maybe something wrong with PyPI version?

**Comment by WeirdCarrotMonster** [comment]
Updated tests to check git version: everything works fine. Something is wrong with PyPI package.

**Comment by serhiy-storchaka** [comment]
Seems there are two bugs here:

1) There is a difference between Python and C implementations.
2) C implementation isn't used in PyPI package.
