### ISSUE TITLE
JSONDecoder hooks enhacement

### ISSUE THREAD

**Issue by Adirio** [simplejson/simplejson#200]
As described in the [Python's standard library issue number 29992](https://bugs.python.org/issue29992), the JSONDecoder parameters are not offering a full parsing capability:

> Though the `JSONDecoder` already has all the hooks internally to allow for a custom `parse_string` (https://github.com/python/cpython/blob/master/Lib/json/decoder.py#L330), this currently is not exposed in the constructor `JSONDecoder.__init__`.
>
> It would be nice to expose it. Currently, I need to do hack it: https://gist.github.com/oberstet/fa8b8e04b8d532912bd616d9db65101a

This can be extended to `parse_array` (e.g. using `tuple` instead of `list`) or even `parse_key` which would be used on JSON object key strings (e.g. `datetime.datetime.utcfromtimestamp` if your keys are timestamps, quite common in databases). This last one is achievable through the `object_hook` and `object_pairs_hook` parameters but it would be way less eficient as the `dict` would already be constructed with the `str` keys and you would need to start `pop`-ing and inserting new items while it could have been done at parse time.

The [last comment](https://bugs.python.org/issue29992#msg309763) offered a patch to add this params. The C accelerated version of it has not been developed yet, as it is not taking into account the new `JSONDecoder` attributes (it wasn't taking some of the old attributes either, that's why the `py_make_scanner` function needs to be used).

**Comment by etrepum** [comment]
object_pairs_hook is almost certainly the right way to implement this, if efficiency is your concern, adding Python code overhead to every single string parse is not aligned with your goals.

**Comment by Adirio** [comment]
I think your point is only valid when the C accelerated version is available and talking about speed. Consider encrypted keys or values and memory efficiency. Once decrypted, they are quite short strings but before decription the space it takes increases exponentially. You will not only have a huge string for the JSON data, but you will also have big strings for every key and value that then you will decrypt once the full dict has been stored.

**Comment by etrepum** [comment]
You're welcome to maintain your own fork that implements these features, but I do not think this is a good solution for this particular problem and will not be accepting a PR that implements them in this way.
