### ISSUE TITLE
`dumps` unnecessarily copies strings, without C extensions (or with ensure_ascii=False)

### ISSUE THREAD

**Issue by richvdh** [simplejson/simplejson#208]
The fix introduced in https://github.com/simplejson/simplejson/commit/d78256146d2831e3a7080b7212d7edb90bc2d611 to work around #144 essentially means, for Python 2, that all strings are copied before serialisation - which is a significant performance overhead.

To explain, consider https://github.com/simplejson/simplejson/blob/d53d0c6/simplejson/encoder.py#L55 and https://github.com/simplejson/simplejson/blob/master/simplejson/encoder.py#L77, each of which is:

```
        if type(s) not in string_types:
```

 `string_types` is `(basestring,)` on Python 2, whereas most strings are either `str` or `unicode`, so the condition fails.

I'm pretty sure this wasn't the intention of that patch.

**Comment by richvdh** [comment]
Given that these lines are only relevant to Python 2, one workaround might be just to replace this with 

```
if type(s) not in (str, unicode):
```

**Comment by etrepum** [comment]
Since you've already tracked this down, do you mind sending a PR with a test to prevent future regression?

**Comment by richvdh** [comment]
Well, a regression test is hard to achieve, since the only effect is a performance regression. I've sent a PR with my proposed fix, anyway.

**Comment by etrepum** [comment]
All Python objects have an identity so you can check to see if they are the same string instance with the `id` function. It’s a bit implementation dependent but you can be pretty sure that if any copying is happening then `id(a) != id(b)`

**Comment by etrepum** [comment]
Looking at the PR, I don't see how we could write a test for that, so nevermind :)

**Comment by etrepum** [comment]
FWIW, due to an optimization in CPython, only unicode objects were actually copied due to this bug.

```python
Python 2.7.6 (default, Nov 23 2017, 15:49:48)                         
[GCC 4.8.4] on linux2                                                 
Type "help", "copyright", "credits" or "license" for more information.
>>> s = 'x' * 1000                                                    
>>> str.__str__(s) is s                                               
True                                                                  
>>> u = u'x' * 1000                                                   
>>> unicode.__getnewargs__(u)[0] is u                                 
False                                                                 
```

**Comment by richvdh** [comment]
ah interesting.

My benchmark loads a bunch of `dicts` from a file with `json.loads` and then measures the time taken to serialise them with `simplejson.dumps`. It turns out that `json.loads` generates `unicode` objects for all strings in the input - hence my benchmark was heavily skewed by the unicode path.
