### ISSUE TITLE
simple question

### ISSUE THREAD

**Issue by global2alex** [simplejson/simplejson#209]
You have an api key in travis.yml, is that really ok? 

> secure: QiadMGAmtPw+Ut7LWqa3U/tImPIgiPH79mM9o8DGBckcacp9HkDYvCGuOjs5hZbCBBuQ6IAkikotS8iCSwHey1GK9jSDbpgKvVGiACdp8HNhitY8V/S3e1UukDlMeu+Q7vCJtynSGX0BJuiOQB8ZQyQ2HEZ7kMQgTLCEO1Uljhc=

**Comment by felixonmars** [comment]
IIRC this is an encrypted key, should be ok :)

**Comment by etrepum** [comment]
Yep, this is an encrypted environment variable and not a raw API key. https://docs.travis-ci.com/user/environment-variables/#Defining-encrypted-variables-in-.travis.yml
