### ISSUE TITLE
Dump dictionary with binary values

### ISSUE THREAD

**Issue by grynko** [simplejson/simplejson#213]
Hi guys!
I had to switch from standard json library to simplejson, so I have an issue.

I have dictionaries whose values may be binary image data. Ideal solution is to encode such values using base64 during the dump:

```python
import json

def encoder(obj):
    if isinstance(obj, bytes):
        return base64.b64encode(obj).decode('ascii')
    raise TypeError()

d = {"key": b"\xff"}
json.dumps(d, default=encoder)
```
After the switch, the same code fails with `UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
`
I tried to solve the issue different ways, including subclassing `simplejson.JSONEncoder` but with no luck.

It seems the library tries to decode each value that may be string, including `bytes` into string with specified encoding (`utf-8` by default) and I couldn't switch this off.

As for me, simplejson should call `default` before trying to decode the value itself.

I will highly appreciate any suggestions on this.

Thanks.

P.S. I'm using Python 3.6.3 and simplejson v3.11.1

**Comment by etrepum** [comment]
Unfortunately there's no workaround for this (other than preprocessing your input). simplejson's Python 3 port was implemented in this way to be close to how it behaves with Python 2. I would see this divergence in behavior to be a mistake (and I'm surprised this is the first report, Python 3 support was introduced in Dec 2012!), but it's not one that can be fixed so quickly for compatibility reasons.

**Comment by serhiy-storchaka** [comment]
I thought passing `encoding=None` should disable the support of bytes by default. But seems this feature was broke in meanwhile. It looks to me that it is not hard to fix this.

**Comment by etrepum** [comment]
That’s a good idea, would be able to make that change without a new major version

**Comment by grynko** [comment]
@serhiy-storchaka, I tried setting `encoding=None`, but it doesn't work: `TypeError: decode() argument 1 must be str, not None`. So it would be really amazing to fix this.
