### ISSUE TITLE
Difference between implementations in handling bytes with overridden decode().

### ISSUE THREAD

**Issue by serhiy-storchaka** [simplejson/simplejson#218]
When serialize or deserialize `bytes` objects in Python 3 or non-ASCII `str` in Python 2, the Python and the C implementations give different results if these objects have overridden the `decode()` method. The Python implementation calls the `decode()` method for converting to unicode. The C implementation directly decodes the bytes content using the specified encoding.

This is similar to #185, but overridden `decode()` is a more rare case than overridden `__str__()`.

There are two options:

* Always call the `decode()` method. This will slowdown and may complicate the C implementation.
* Always bypass the `decode()` method (using `text_type(x, encoding)` instead of `x.decode(encoding)` in Python code).

I prefer the latter option, but maybe there is a value of the former option.

**Comment by etrepum** [comment]
The latter option sounds good to me

**Comment by serhiy-storchaka** [comment]
Implemented by #219.
