### ISSUE TITLE
segfault installing on python3.7

### ISSUE THREAD

**Issue by h4ck3rm1k3** [simplejson/simplejson#227]
python3.7 -m pip install simplejson
```
Collecting simplejson
Installing collected packages: simplejson
Successfully installed simplejson-3.16.0
Segmentation fault
```

See bug report on debian for details 
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=902835

It might be because  Py_Initialize() is not being called, see https://docs.python.org/3.7/whatsnew/3.7.html
"""
Changes to the startup sequence and the management of dynamic memory allocators mean that the long documented requirement to call Py_Initialize() before calling most C API functions is now relied on more heavily, and failing to abide by it may lead to segfaults in embedding applications. See the Porting to Python 3.7 section in this document and the Before Python Initialization section in the C API documentation for more details.
"""

**Comment by h4ck3rm1k3** [comment]
It only occurs when installing from pip but not from git!

**Comment by etrepum** [comment]
Installation doesn’t really run any simplejson code (outside of some stuff in setup.py to detect a compiler), so the problem is likely elsewhere as you’ve noted.

**Comment by h4ck3rm1k3** [comment]
So this module seems to be the common thread in the two other modules that use it but something in the pypi.org version is causing it to crash. I have a workaround for now, it is not even important, just odd.

**Comment by etrepum** [comment]
It's probably a bug in pip.
