### ISSUE TITLE
simplejson.dumps default param not working !

### ISSUE THREAD

**Issue by toplinuxsir** [simplejson/simplejson#228]
```
def df_func(obj):
    print(type(obj))
    return str(obj)


simplejson.dumps(dict(x=1, y=2, c="hello"), default=df_func)
```

the df_func not called when dumps

**Comment by etrepum** [comment]
This is the expected behavior of default. It is only called for objects that can not otherwise be serialized.

>   If specified, *default* should be a function that gets called for objects
>   that can't otherwise be serialized.  It should return a JSON encodable
>   version of the object or raise a :exc:`TypeError`.
