### ISSUE TITLE
Running setup.py install for simplejson ... error on python3.7.0

### ISSUE THREAD

**Issue by alirezaimi** [simplejson/simplejson#232]
Hi
I want to install simplejson lib for Python 3.7.0 64bit and this is i've got :

	PS C:\> pip install simplejson
	Collecting simplejson
	  Using cached https://files.pythonhosted.org/packages/e3/24/c35fb1c1c315fc0fffe61ea00d3f88e85469004713dab488dee4f35b0af
	f/simplejson-3.16.0.tar.gz
	Installing collected packages: simplejson
	  Running setup.py install for simplejson ... error
		Complete output from command c:\python\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\dvp7\\AppD
	ata\\Local\\Temp\\1\\pip-install-59fej34i\\simplejson\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read
	().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\dvp7\AppData\Local\T
	emp\1\pip-record-qklmgunh\install-record.txt --single-version-externally-managed --compile:
		running install
		running build
		running build_py
		creating build
		creating build\lib.win-amd64-3.7
		creating build\lib.win-amd64-3.7\simplejson
		copying simplejson\compat.py -> build\lib.win-amd64-3.7\simplejson
		copying simplejson\decoder.py -> build\lib.win-amd64-3.7\simplejson
		copying simplejson\encoder.py -> build\lib.win-amd64-3.7\simplejson
		copying simplejson\errors.py -> build\lib.win-amd64-3.7\simplejson
		copying simplejson\ordered_dict.py -> build\lib.win-amd64-3.7\simplejson
		copying simplejson\raw_json.py -> build\lib.win-amd64-3.7\simplejson
		copying simplejson\scanner.py -> build\lib.win-amd64-3.7\simplejson
		copying simplejson\tool.py -> build\lib.win-amd64-3.7\simplejson
		copying simplejson\__init__.py -> build\lib.win-amd64-3.7\simplejson
		creating build\lib.win-amd64-3.7\simplejson\tests
		copying simplejson\tests\test_bigint_as_string.py -> build\lib.win-amd64-3.7\simplejson\tests
		copying simplejson\tests\test_bitsize_int_as_string.py -> build\lib.win-amd64-3.7\simplejson\tests
		copying simplejson\tests\test_check_circular.py -> build\lib.win-amd64-3.7\simplejson\tests
		copying simplejson\tests\test_decimal.py -> build\lib.win-amd64-3.7\simplejson\tests
		copying simplejson\tests\test_decode.py -> build\lib.win-amd64-3.7\simplejson\tests
		copying simplejson\tests\test_default.py -> build\lib.win-amd64-3.7\simplejson\tests
		copying simplejson\tests\test_dump.py -> build\lib.win-amd64-3.7\simplejson\tests
		copying simplejson\tests\test_encode_basestring_ascii.py -> build\lib.win-amd64-3.7\simplejson\tests
		copying simplejson\tests\test_encode_for_html.py -> build\lib.win-amd64-3.7\simplejson\tests
		copying simplejson\tests\test_errors.py -> build\lib.win-amd64-3.7\simplejson\tests
		copying simplejson\tests\test_fail.py -> build\lib.win-amd64-3.7\simplejson\tests
		copying simplejson\tests\test_float.py -> build\lib.win-amd64-3.7\simplejson\tests
		copying simplejson\tests\test_for_json.py -> build\lib.win-amd64-3.7\simplejson\tests
		copying simplejson\tests\test_indent.py -> build\lib.win-amd64-3.7\simplejson\tests
		copying simplejson\tests\test_item_sort_key.py -> build\lib.win-amd64-3.7\simplejson\tests
		copying simplejson\tests\test_iterable.py -> build\lib.win-amd64-3.7\simplejson\tests
		copying simplejson\tests\test_namedtuple.py -> build\lib.win-amd64-3.7\simplejson\tests
		copying simplejson\tests\test_pass1.py -> build\lib.win-amd64-3.7\simplejson\tests
		copying simplejson\tests\test_pass2.py -> build\lib.win-amd64-3.7\simplejson\tests
		copying simplejson\tests\test_pass3.py -> build\lib.win-amd64-3.7\simplejson\tests
		copying simplejson\tests\test_raw_json.py -> build\lib.win-amd64-3.7\simplejson\tests
		copying simplejson\tests\test_recursion.py -> build\lib.win-amd64-3.7\simplejson\tests
		copying simplejson\tests\test_scanstring.py -> build\lib.win-amd64-3.7\simplejson\tests
		copying simplejson\tests\test_separators.py -> build\lib.win-amd64-3.7\simplejson\tests
		copying simplejson\tests\test_speedups.py -> build\lib.win-amd64-3.7\simplejson\tests
		copying simplejson\tests\test_str_subclass.py -> build\lib.win-amd64-3.7\simplejson\tests
		copying simplejson\tests\test_subclass.py -> build\lib.win-amd64-3.7\simplejson\tests
		copying simplejson\tests\test_tool.py -> build\lib.win-amd64-3.7\simplejson\tests
		copying simplejson\tests\test_tuple.py -> build\lib.win-amd64-3.7\simplejson\tests
		copying simplejson\tests\test_unicode.py -> build\lib.win-amd64-3.7\simplejson\tests
		copying simplejson\tests\__init__.py -> build\lib.win-amd64-3.7\simplejson\tests
		running build_ext
		building 'simplejson._speedups' extension
		error: [WinError 3] The system cannot find the path specified: 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.
	0\\VC\\PlatformSDK\\lib'

		----------------------------------------
	Command "c:\python\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\dvp7\\AppData\\Local\\Temp\\1\\pip
	-install-59fej34i\\simplejson\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n')
	;f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\dvp7\AppData\Local\Temp\1\pip-record-qklmgun
	h\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\dvp7\AppData\Lo
	cal\Temp\1\pip-install-59fej34i\simplejson\

**Comment by etrepum** [comment]
This looks like the sort of error you'd get if you did not have an environment configured properly to compile C extensions. At this time, a precompiled version of simplejson for Python 3.7 is not available. The version matrix will likely be updated on the next release to include Python 3.7.

**Comment by alirezaimi** [comment]
What can i do about my env to compile c exts ?

**Comment by alirezaimi** [comment]
Thanks to this [post](https://ask.streamsets.com/question/598/do-i-need-ms-visual-studio-14-to-install-streamsets-sdk-for-python-in-windows-environment/) i installed vs dev tools and problem solved .
thanks.
