### ISSUE TITLE
security issues as reported by 'bandit'

### ISSUE THREAD

**Issue by saobao913** [simplejson/simplejson#242]
simplejson-3.16.0

[main]	INFO	profile include tests: None
[main]	INFO	profile exclude tests: None
[main]	INFO	cli include tests: None
[main]	INFO	cli exclude tests: None
[main]	INFO	running on Python 3.6.7
Run started:2019-01-31 07:16:33.106337

Test results:
>> Issue: [B310:blacklist] Audit url open for permitted schemes. Allowing use of file:/ or custom schemes is often unexpected.
   Severity: Medium   Confidence: High
   Location: simplejson-3.16.0/scripts/artifacts.py:12
   More Info: https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b310-urllib-urlopen
11	def get_json(url):
12	    return json.loads(urlopen(url).read().decode('utf-8'))
13	

--------------------------------------------------

Code scanned:
	Total lines of code: 1930
	Total lines skipped (#nosec): 0

Run metrics:
	Total issues (by severity):
		Undefined: 0.0
		Low: 10.0
		Medium: 1.0
		High: 0.0
	Total issues (by confidence):
		Undefined: 0.0
		Low: 0.0
		Medium: 0.0
		High: 11.0
Files skipped (0):

**Comment by etrepum** [comment]
This is a false positive, this script is only used administratively for releases and not with untrusted input.
