### ISSUE TITLE
Installing simplejson twice crashes

### ISSUE THREAD

**Issue by dankegel** [simplejson/simplejson#245]
Looks like #114 was real?  

See also https://bugs.python.org/issue27542 which has the same stack backtrace as I'm seeing.
Here's a reliable way to reproduce it: just run 'pip install simplejson' twice on a fresh ubuntu 18.04 system.

```
$ lxc launch ubuntu:18.04 snafu
$ lxc exec snafu bash
# apt update
# apt install python-pip
# su ubuntu
$ cd
$ pip --version
pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)
$ pip install simplejson
$ pip install simplejson
Segmentation fault (core dumped)
```
The problem does not occur with the ubuntu 19.04 daily build, which has a much newer version of pip (18.1) and a somewhat newer version of python (2.7.16 vs. 2.7.15rc1).

It also does not happen with pip 19.0.3 (installed by uninstalling python-pip, then running python get-pip.py --user) on ubuntu 18.04.  So it does seem like a pip bug.  But... is there something simplejson is doing to tickle that bug?   Very few packages have this problem.

**Comment by etrepum** [comment]
https://github.com/simplejson/simplejson/issues/114#issuecomment-130364736

This is a bug in pip, nothing I can do about it.

**Comment by etrepum** [comment]
It’s because that version of pip depends on simplejson when present and does something unsafe during the install. I was never able to repro but I don’t think it can be fixed in simplejson either way.

**Comment by dankegel** [comment]
Thanks for the explanation!

**Comment by dankegel** [comment]
Fun fact: pip 9 in ubuntu has the simplejson dependency commented out:
https://github.com/pypa/pip/blob/master/tasks/vendoring/patches/requests.patch
So that's not it.  But cherrypicking https://github.com/pypa/pip/commit/018f03aab448231462b6c013a65d60a35e06e65a.patch seems to fix the crash.  I'll try to verify and submit an SRU for Ubuntu 18.04.

**Comment by dankegel** [comment]
Any Ubuntu 18.04 users who need a fix for this, see https://bugs.launchpad.net/ubuntu/+source/python-pip/+bug/1821483 for a link to a PPA with a fix.
