### ISSUE TITLE
float 1.e-5 can't be interpreted / Error with REGEXP and floats!!!!

### ISSUE THREAD

**Issue by rspadim** [simplejson/simplejson#249]
https://github.com/simplejson/simplejson/blob/master/simplejson/scanner.py#L16
this json can't be interpreted
---
ERRORS:
json.loads("1.e-1")
json.loads("1.e-01")
json.loads("1.e-001")

OK:
json.loads("1.0e-1")
---
the problem:    1. without 0 after it should be considered a number (javascript do it right)

**Comment by rspadim** [comment]
chrome console> 1.e-1
output> 0.1

**Comment by rspadim** [comment]
maybe instead of 

    r'(-?(?:0|[1-9]\d*))(\.\d+)?([eE][-+]?\d+)?',

should be

    r'(-?(?:0|[1-9]\d*))(\.\d*)?([eE][-+]?\d+)?',

**Comment by etrepum** [comment]
The parser correctly handles all valid JSON. It is not a JavaScript parser. See https://tools.ietf.org/html/rfc7159#section-6 for the spec.

**Comment by rspadim** [comment]
nice thanks
