### ISSUE TITLE
Officially support Python 3.7+

### ISSUE THREAD

**Issue by shaib** [simplejson/simplejson#258]
Issues #238 and #240 explain that the 3.16.1 release was rolled back because of #237; there was a problem with linux wheels, and since that was the only new feature, the release was just rolled back.

Except that there was another little feature in 3.16.1, and that was official support (and automatic tests) for Python 3.7.

Would you consider releasing a 3.16.x supporting the newer Pythons without the wheels?

**Comment by etrepum** [comment]
I was planning to do a release this weekend, should be sorted soon

**Comment by etrepum** [comment]
Note that the tests are run with Python 3.7 and Python 3.8 in CI here and are in a passing state with the exact same code, although I understand that you may want wheels to be available for those versions.

**Comment by shaib** [comment]
Cool, thanks. Will use 3.16.0 for now, and upgrade when it's available.
