### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Mettfisto** [simplejson/simplejson#259]
When trying to install it twice or update simplejson via
"pip3 install simplejson --upgrade" or "pip3 install simplejson" , this error appears.
Tried on Ubuntu 18.04 LTS

**Comment by etrepum** [comment]
Could you report this with pip? The installation process for simplejson doesn’t run any code that could cause this.

**Comment by etrepum** [comment]
See also #245
