### ISSUE TITLE
Bug: use_decimal does not convert numbers without . to Decimal

### ISSUE THREAD

**Issue by mathiasrabe** [simplejson/simplejson#262]
Hi,

I'm using simplejson 3.17.0. I found the following bug (or is it intended?):

My json-file looks like this:

```
{
  "one": 1.0,
  "two": 2
}
```

And my python script like this:

```
import simplejson as json

filepath = "some.json"

with open(filepath, 'r') as infile:
    dictionary = json.load(infile, use_decimal=True)
    print(dictionary)
```

I will get this:

`{'one': Decimal('1.0'), 'two': 2}`

But I expected this:

`{'one': Decimal('1.0'), 'two': Decimal('2.0')}`

**Comment by etrepum** [comment]
This is expected behavior, it does not change how integers are parsed.
