### ISSUE TITLE
Wheel support for aarch64

### ISSUE THREAD

**Issue by odidev** [simplejson/simplejson#263]
**Summary**
Installing simplejson on aarch64 via pip using command "pip3 install simplejson" tries to build wheel from source code

**Problem description**
simplejson don't have wheel for aarch64 on PyPI repository. So, while installing simplejson via pip on aarch64, pip builds wheel for same resulting in it takes more time to install simplejson. Making wheel available for aarch64 will benefit aarch64 users by minimizing simplejson installation time.

**Expected Output**
Pip should be able to download simplejson wheel from PyPI repository rather than building it from source code.

@simplejson-team, please let me know if I can help you building wheel/uploading to PyPI repository. I am curious to make simplejson wheel available for aarch64. It will be a great opportunity for me to work with you.

**Comment by etrepum** [comment]
I would happily accept a PR that produces wheels for any additional architectures.

**Comment by odidev** [comment]
Thanks @etrepum I will work and update you.

**Comment by odidev** [comment]
@etrepum I have successfully added the jobs for arm64 in travis.yml and all tests are passing successfully, please have a look at the Travis build logs: https://travis-ci.com/github/odidev/simplejson/builds/175563068

I have added jobs for Python version 3.6, 3.7, and 3.8 only Travis.yml diff: https://github.com/odidev/simplejson/commit/93d013b30631ee5633c799e81b75c28c5088a971, Please have a look and suggest if anything else needs to be done from my end or I can go ahead to raise the PR for the same.

**Comment by etrepum** [comment]
Great, the easiest way for me to review it is if you create the PR, but the travis output looks good

**Comment by odidev** [comment]
@etrepum I have raised the pull request, please have a look: https://github.com/simplejson/simplejson/pull/264
