### ISSUE TITLE
Feature request: JSON5 support

### ISSUE THREAD

**Issue by dcoles** [simplejson/simplejson#265]
From the [JSON5 webpage](https://json5.org/):
> The JSON5 Data Interchange Format (JSON5) is a superset of JSON that aims to alleviate some of the limitations of JSON by expanding its syntax to include some productions from ECMAScript 5.1.

**Short example**
```json5
{
  // comments
  unquoted: 'and you can quote me on that',
  singleQuotes: 'I can use "double quotes" here',
  lineBreaks: "Look, Mom! \
No \\n's!",
  hexadecimal: 0xdecaf,
  leadingDecimalPoint: .8675309, andTrailing: 8675309.,
  positiveSign: +1,
  trailingComma: 'in objects', andIn: ['arrays',],
  "backwardsCompatible": "with JSON",
}
```

**Why:** JSON is frequently used as a configuration file format, but suffers from multiple limitations (lack of comments, strict comma rules, single form of quoting) that make it painful for humans to read, write and maintain. Other configuration file formats exist ([YAML](https://yaml.org/), [TOML](https://toml.io/), etc.), but JSON remains one of the most portable and widely accepted format.

As JSON5 is a strict superset of JSON, this doesn't introduce any incompatibilities in reading existing JSON files and follow the [principle of "Be conservative in what you send, be liberal in what you accept"](https://en.wikipedia.org/wiki/Robustness_principle).

As the [official JSON library in Python](https://docs.python.org/3/library/json.html), simplejson has the advantage of a wide user base, maturity and trust. Further there are significant advantages for Python's JSON and JSON5 support to share a single code-base (reduced maintenance, compatibility, security/code quality, code reuse, etc.)

**Why not**: simplejson has always positioned itself as "a simple, fast, complete, correct and extensible" JSON encoder/decoder. Supporting JSON5 may introduce substantial complexity and maintenance burden, especially if the industry standardises on another form of JSON superset.

If this is the case, this issue would be used to explain why support is out-of-scope for simplejson.

**Why not … library?**

Several Python JSON5 libraries already exist ([dpranke/pyjson5](https://github.com/dpranke/pyjson5), [Kijewski/pyjson5](https://github.com/Kijewski/pyjson5)), but have limitations such as [slowness](https://github.com/dpranke/pyjson5#known-issues), lack of support for [PyPy](https://github.com/Kijewski/pyjson5#compatibility) or dependencies that would prevent inclusion in the Python Standard Library.

**Comment by etrepum** [comment]
Thanks for bringing this up! I think at this time, it would be out of scope for simplejson. I think it would introduce significant complexity and maintenance burden, the options available in simplejson are already a bit of a mess (nearly 15 years worth). The backwards compatibility burden that simplejson has (back to 2.5!) would also make this undertaking harder than it really ought to be.
