### ISSUE TITLE
Suggest: add GitHub topics

### ISSUE THREAD

**Issue by imba-tjd** [simplejson/simplejson#268]
For example https://github.com/topics/json

**Comment by etrepum** [comment]
Good idea, done

**Comment by mhadigamr** [comment]
Hi

في الاثنين، ١٢ أكتوبر ٢٠٢٠ ٩:٠٢ م Bob Ippolito <notifications@github.com>
كتب:

**Comment by serhiy-storchaka** [comment]
Maybe add also [json-parser](https://github.com/topics/json-parser) and [json-serializer](https://github.com/topics/json-serializer)?

**Comment by etrepum** [comment]
@serhiy-storchaka good idea, will add those as well
