### ISSUE TITLE
JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

### ISSUE THREAD

**Issue by Rupam07** [simplejson/simplejson#269]
I tried replacing the replace("\'", "\"") in json object but still keeps throwing the same error

Please help me with this

**Comment by etrepum** [comment]
This means the document you are trying to parse is not valid JSON. From the error it looks like the document starts with a `{` but the next non-whitespace character is not a `"` or `}`. simplejson will not parse documents that are not valid JSON.
