### ISSUE TITLE
Why use c extension to speedup

### ISSUE THREAD

**Issue by chenqhxyz** [simplejson/simplejson#272]
Hi,

This is just a general question about why you guys decided to use regular cpython API to implement c extension (_speedup.c) rather than cython, ctypes, cffi...

I think ctypes and cffi is easier to maintain and cython is faster.

Thanks!

**Comment by etrepum** [comment]
cython and cffi did not even exist 15 years ago when this project started. ctypes is not relevant and even if it was it did not ship with Python at the time.
