### ISSUE TITLE
simplejson does not support latin special characters 

### ISSUE THREAD

**Issue by bmalbusca** [simplejson/simplejson#276]
As the similarity with json package, the `json.dumps(resp, ensure_ascii=False,ignore_nan=True)` almost does the job. The problem is the latin characters `ç` and accents variants. Any solution for this? 

Example:

```python
# using import json
[{"type": "Aduação", "subtype": "Bombagem", "flow": 42.0, "start": "WN_ALQUEVA_B0", "startcoord": {"lng": -7.496078, "lat": 38.206491}, "end": "WN_ALQUEVA_E4", "endcoord": {"lng": -7.575005, "lat": 38.337011}}, {"type": "Aduação", "subtype": "Bombagem", "flow": 37.0, "start": "WN_ALQUEVA_B1", "startcoord": {"lng": -7.614198, "lat": 38.333779}, "end": "WN_ALQUEVA_B2", "endcoord": {"lng": -7.738848, "lat": 38.365344}}, ...
```

```python
# using simplejson
[{"type": "AduaÃ§Ã£o", "subtype": "Bombagem", "flow": 42.0, "start": "WN_ALQUEVA_B0", "startcoord": {"lng": -7.496078, "lat": 38.206491}, "end": "WN_ALQUEVA_E4", "endcoord": {"lng": -7.575005, "lat": 38.337011}}, {"type": "AduaÃ§Ã£o", "subtype": "Bombagem", "flow": 37.0, "start": "WN_ALQUEVA_B1", "startcoord": {"lng": -7.614198, "lat": 38.333779}, "end": "WN_ALQUEVA_B2", "endcoord": {"lng": -7.738848, "lat": 38.365344}}, {"type": "AduaÃ§Ã£o", "subtype": "Gravidade", "flow": 32.0, "start": "WN_ALQUEVA_B2", "startcoord": {"lng": -7.738848, "lat": 38.365344}, "end": "WN_ALQUEVA_E5", "endcoord": {"lng": -7.74176, "lat": 38.363315}}, {"type": "AduaÃ§Ã£o", "subtype": "Gravidade", "flow": 40.0, "start": "WN_ALQUEVA_B3", "startcoord": {"lng": -7.887377, "lat": 38.299423}, "end": "WN_ALQUEVA_C24", "endcoord": {"lng": 

```

The `Aduação` appears as `AduaÃ§Ã£o`.

**Comment by etrepum** [comment]
There isn't enough information in this issue to reproduce this, such as Python version, simplejson version, code used to create the issue, and the operating system. I am certain that this is not a bug in simplejson, but there are some differences in simplejson and json especially depending on the versions of each and which Python interpreter you are using.

It looks like it's likely that your terminal settings or something else related to I/O do not match your expectations. This is the output you would see if you were decoding utf-8 data as latin-1.

```python
>>> 'Aduação'.encode('utf8').decode('latin1')
'AduaÃ§Ã£o'
```

**Comment by bmalbusca** [comment]
> There isn't enough information in this issue to reproduce this, such as Python version, simplejson version, code used to create the issue, and the operating system. I am certain that this is not a bug in simplejson, but there are some differences in simplejson and json especially depending on the versions of each and which Python interpreter you are using.
> 
> It looks like it's likely that your terminal settings or something else related to I/O do not match your expectations. This is the output you would see if you were decoding utf-8 data as latin-1.
> 
> ```python
> >>> 'Aduação'.encode('utf8').decode('latin1')
> 'AduaÃ§Ã£o'
> ```

That's true.  The bug appears to be the web browser.  Thank you very much.
