### ISSUE TITLE
unable to install :(

### ISSUE THREAD

**Issue by f5swb** [simplejson/simplejson#277]
hello, 

sudo pip3 install simplejson==3.17.2 // also  sudo pip3 install simplejson

Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting simplejson==3.17.2
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(185090184, '[X509] no certificate or crl found (_ssl.c:4053)'))': /simple/simplejson/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 

  Could not find a version that satisfies the requirement simplejson==3.17.2 (from versions: )
No matching distribution found for simplejson==3.17.2

python3 --version
Python 3.7.3
python3 -m pip --version
pip 18.1 from /usr/lib/python3/dist-packages/pip (python 3.7)

Any idea ?

Many thanks

**Comment by etrepum** [comment]
It looks like there’s a problem establishing a SSL connection. I would suggest asking the question in a forum where people are more familiar with pip, as this is not an issue with simplejson itself.

**Comment by f5swb** [comment]
you're right bob, many thanks for the answer just did a sudo apt-get install --reinstall ca-certificates all is ok now.
Many thanks.
