### ISSUE TITLE
Simplejson wheels distribution

### ISSUE THREAD

**Issue by chenqhxyz** [simplejson/simplejson#278]
Hi team,

I noticed that [simplejson](https://pypi.org/project/simplejson/3.17.2/#files) in PYPI includes wheel type, I am kind of curious of how you manage to create these much wheels among multiple platforms (e.g. create virtual machines to generate these wheels)?

**Comment by etrepum** [comment]
Everything you need to know is right here in the repository, see [.travis.yml](https://github.com/simplejson/simplejson/blob/master/.travis.yml) and [appveyor.yml](https://github.com/simplejson/simplejson/blob/master/appveyor.yml)

**Comment by chenqhxyz** [comment]
Thanks!
