### ISSUE TITLE
TypeError: _init_() got an unexpected keyword argument 'encoding' 

### ISSUE THREAD

**Issue by bovlb** [simplejson/simplejson#279]
I have not been able to boil this down to a simple reproduction, but it appears that, under some circumstances,  JSON parsing falls back onto a code path that passes the `encoding` parameter to json.JSONDecoder.  That parameter was supported in Python 2, but dropped in Python 3 as part of the Unicode changes.
 
https://github.com/simplejson/simplejson/blob/master/simplejson/__init__.py#L542

**Comment by etrepum** [comment]
Are you sure that you’re reporting this in the right place? It’s unclear whether you’re talking about the stdlib json or this simplejson package. The stdlib json was forked from here many years ago and they are not really synchronized.

If you were using simplejson it would be helpful to include how it was invoked, a more complete traceback, and the versions of everything (OS, architecture, Python, and simplejson).

**Comment by bovlb** [comment]
Ubuntu 18.04.1 x86_64
Python 3.6.9
simplejson==3.13.2

I'm afraid I can't give a full reproduction or traceback because it depends on a peculiar misconfiguration of our proprietary network services that has now been resolved, but I thought you would like to know.

```
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 535, in loads
    return cls(encoding=encoding, **kw).decode(s)
```

**Comment by etrepum** [comment]
I’d need to see the part where simplejson is invoked to have any chance of reproducing it.

What’s probably happening is that a subclass of the stdlib json module decoder is passed to the simplejson loads function with cls. That won’t work, and it’s best not to use subclassing at all. I wouldn’t consider that to be a bug in simplejson, and it’s a bit of an anti pattern to do too much runtime type checking in Python.

**Comment by bovlb** [comment]
Yes, I think that's what's happening.  It's not really my code.  

OK.  Thanks for responding.
