### ISSUE TITLE
Wheels for python 3.9

### ISSUE THREAD

**Issue by komendart** [simplejson/simplejson#282]
Hi!

As I can see wheel distribution is available on pypi only for python <= 3.8. When do you plan to provide py39 wheels too?

**Comment by etrepum** [comment]
Well I think at this point the blocker is going to be that travis-ci.org is no longer available, so the CI and release process needs to be moved over to something else before new wheels can be built.

**Comment by etrepum** [comment]
I think I have resolved this with #283
