### ISSUE TITLE
GA test simplejson on python 3.10 is failed

### ISSUE THREAD

**Issue by sunhailin-Leo** [simplejson/simplejson#290]
* Github Actions can not test simplejson on python3.10 in my repo
![image](https://user-images.githubusercontent.com/17564655/141760534-68ff6aab-160c-4cea-a8eb-5d4bff01e993.png)

**Comment by etrepum** [comment]
Your problem is that simplejson is not installed, there's nothing that we can change in simplejson to resolve that issue. I don't know what you're using that requires simplejson, but you should start there.
