### ISSUE TITLE
Design Question about `JSONDecodeError`

### ISSUE THREAD

**Issue by daskol** [simplejson/simplejson#295]
I am just curious why `simplejson.JSONDecodeError` is not derived from `json.JSONDecodeError`? I am interested why the code in snippet below can be undesirable.
```python
import json
import simplejson


def decode_something():
    try:
        # Actual decoding of a JSON content with any JSON decoder (e.g json or
        # simplejson).
        pass
    except json.JSONDecodeError:
        # Report error or recover.
        pass

```

**Comment by etrepum** [comment]
simplejson predates the json module in the standard library, there's no dependency at all between them. The json standard library was forked from simplejson many years ago and they are maintained separately.

**Comment by daskol** [comment]
Thanks! It was unexpected. Nowadays, modules are more often excluded from than included to stdlib. 😃

**Comment by DanielNoord** [comment]
@etrepum Would you consider adding this inheritance to prevent the issue in `requests` as described here: https://github.com/psf/requests/issues/4842

**Comment by etrepum** [comment]
No, it would only cause different issues.

**Comment by daskol** [comment]
What is the issue? The situation when someone wants to distinguish between `json.JSONDecodeError` and `simplejson.JSONDecodeError` seems real but higly uncommon.

**Comment by etrepum** [comment]
Someone interested in catching either can use ValueError, there’s no guarantee that they have the same interface especially as both evolve over time. They are already more than just nominally different, simplejson’s takes an extra argument.

**Comment by DanielNoord** [comment]
I totally understand that this is complicated and not something you would want to add, but you must also acknowledge that `ValueError` is a bit too "large" sometimes.
However, clearly the issue here is with `requests` as they change behaviour without the user being able to impact that. S
ince they seem unwilling to change (or release a breaking major version) I thought I would try here.
Thanks for taking the time to respond, appreciated!😄

**Comment by etrepum** [comment]
It’s a breaking change for either package, but if simplejson does this it would not only potentially break old code, it can break at any time in the future when the standard library or simplejson diverge. This package has been around for over 17 years, before a fork of it became the json module in the standard library. It makes much less sense to add hacks here to compensate for mistakes elsewhere.
