### ISSUE TITLE
Passing a NamedTuple **class** rather than instance to `.dumps` results in an error

### ISSUE THREAD

**Issue by ng-henry** [simplejson/simplejson#301]
simplejson has functionality to encode namedtuple instances using their `_asdict()` method. However, when passing the underlying namedtuple **type** to `json.dumps`, there's an error: `._asdict() missing 1 required positional argument: 'self'`

https://github.com/simplejson/simplejson/blob/8dce5b06d3faf9cc439a56dfa3cbdcde2dd8c8ec/simplejson/_speedups.c#L385-L399

The reason is that `_is_namedtuple` only checks for the existence of a method named `_asdict()`. Calling `_asdict()` from the object instance requires no further arguments as `self` is already provided. However, calling `_asdict()` from the namedtuple class requires an additional argument, `self`. 

To fix this, `_is_namedtuple` function should further check that the object is an instance rather than a class, or that the `_asdict()` function is indeed callable with zero arguments.

**Comment by etrepum** [comment]
What is the intended use case of passing such a nametuple class through the encoder? What do you expect to happen here other than perhaps a different error message?

**Comment by ng-henry** [comment]
I'm working on capturing all the arguments of a given function call and serializing them to JSON. Since the arguments can be anything, I'd expect simplejson to encode builtin objects and call the `default` function for all the other things it cannot encode. 

For example, if I pass in a random class (**not NamedTuple**), then simplejson would call `default` and let user handle it themselves. But for NamedTuple, simplejson crashes and does not let user specify how to encode.

**Comment by etrepum** [comment]
This is implemented in v3.18.0
