### ISSUE TITLE
simplejson/_speedups.c is missing in 3.18.2 sdist

### ISSUE THREAD

**Issue by mgorny** [simplejson/simplejson#309]
The [simplejson-3.18.2.tar.gz](https://files.pythonhosted.org/packages/0e/4d/bc45300f0c6ae36462166faec34b62827b8e0a9f71c987ee36e7e5435294/simplejson-3.18.2.tar.gz) archive published on PyPI seems to miss the `simplejson/_speedups.c` file needed to build the C extension.

If I build it with `REQUIRED_SPEEDUPS=1`, I get the following error:

```
2023-02-05 17:13:45,367 root INFO x86_64-pc-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -march=znver2 --param=l1-cache-size=32 --param=l1-cache-line-size=64 -O2 -pipe -frecord-gcc-switches -fPIC -I/usr/include/python3.9 -c simplejson/_speedups.c -o build/temp.linux-x86_64-cpython-39/simplejson/_speedups.o
cc1: fatal error: simplejson/_speedups.c: No such file or directory
compilation terminated.
```

**Comment by etrepum** [comment]
Thank you for the report, in the meantime you can use 3.18.1, the only changes were related to the build process. A new version that resolves this issue will be released later today.

**Comment by mgorny** [comment]
Don't worry, we're generally using GitHub snapshots anyway because sdists are missing files too often (and it's usually hard to notice) :-(.

**Comment by etrepum** [comment]
I'm sure it would've taken some time for someone else to notice, I certainly wouldn't! Testing a sdist isn't something that I've ever really done without someone else reporting it, but maybe I should just add a CI step to do it.

**Comment by mgorny** [comment]
Believe me, I wouldn't have noticed it either. I've only done so by accident because I've noticed you've made speedups optional, and wanted to make them optional in Gentoo as well — and noticed that after enabling them I didn't get the extensions ;-).
