### ISSUE TITLE
JSON is not a subset of YAML

### ISSUE THREAD

**Issue by SmartHypercube** [simplejson/simplejson#318]
https://github.com/simplejson/simplejson/blob/532f41f870f6287ffe73882a313c2cc9c70f3cb6/index.rst?plain=1#L153-L156

1. **JSON is not a subset of YAML 1.2.**

The YAML 1.2 spec is wrong about this. "Subset" means as long as a string is legal JSON, it should also be legal YAML 1.2. However:
```python
>>> import json
>>> import ruamel.yaml  # YAML 1.2 parser
>>> json.loads('{"a"\n:0}')
{'a': 0}
>>> yaml = ruamel.yaml.YAML(typ='rt')
>>> yaml.load('{"a"\n:0}')
Traceback (most recent call last):
...
ruamel.yaml.parser.ParserError: while parsing a flow mapping
  in "<unicode string>", line 1, column 1:
    {"a"
    ^ (line: 1)
expected ',' or '}', but got ':'
  in "<unicode string>", line 2, column 1:
    :0}
    ^ (line: 2)
```
There are many other examples. This is not the only one.

2. **The JSON produced by this module's default settings is not a subset of YAML 1.0 and 1.1.**
```python
>>> import json
>>> import yaml  # YAML 1.1 parser
>>> json.dumps(1e20)
'1e+20'
>>> yaml.safe_load('1e+20')
'1e+20'
```
Note that `1e+20` is parsed as a number in JSON, but parsed as a string in YAML 1.1.

**Comment by etrepum** [comment]
A PR with the documentation changes that you would recommend would be appreciated, nobody else has brought up these edge cases in the (at least) 9 years that this note has been present.
