### ISSUE TITLE
Would you be open for a PR with a "preprocess" object hook in the encoder?

### ISSUE THREAD

**Issue by jmoraleda** [simplejson/simplejson#323]
I have an encoding use case, in which neither the `default` nor `for_json` hooks suffice.

The use case is a RAD framework in which the user can serialize _arbitrary_ nested structures. The framework exchanges data between Python and Java in json. I want my users to be able to serialize/deserialize dicts with _arbitrary_ keys in both languages, whether by themselves or nested in other dicts or lists or other iterables, such as sets.

`default` is not called for dicts or other others that are serializable for default, and is called only _after_ the standard serialization has taken place, and not recursively. `for_json` is called early in the process, and recursively in the way I want, but it requires the object to be serialized to provide the transformation method, instead of allowing to pass a transformation method to the encoder like `default` does.

What I have implemented is a `preprocess` hook that takes a callable, like default but calls it for every value to be encoded, before it is processed, in the same places that `for_json` is currently called.

I would be happy to submit a PR if you think this would be of general usefulness.

**Comment by etrepum** [comment]
I think generally this kind of thing would be too much of a performance burden for most use cases, so I wouldn't want to introduce it into the core. Generally I think a better approach for arbitrary transformations before encoding would be to have some sort of schema to handle it top-down rather than branching on every value.

For your use case without modifying simplejson I would add a wrapper around primitive values that should be transformed before encoding such that default (or a for_json method) could handle it. For decoding you already have object_hook or object_pairs_hook so you could add the wrappers at that point on deserialization.

**Comment by jmoraleda** [comment]
Thank you @etrepum 

I was thinking of implementing this functionality in simplejson by adding in three places:
```python
 preprocess = _preprocess and call_preprocess(value, _preprocess)
 if preprocess:
     chunks = _iterencode(preprocess[0], _current_indent_level)
 else:
     # The existing code ...
     for_json = _for_json and call_method(value, 'for_json')
    ...
```
Do you still feel that for users that do not set `preprocess` this extra `if` test (per value, but only for "complex" values, since it happens after encoding the "simple" values) is too much of a performance burden?

(A similar change would have to be done in the c speed ups, and a few other lines would need to be added, but only during the creation of the encoder so they would not have any measurable impact on speed).

For completeness, the `preprocess` function that I want to use would be:

``` python
def preprocess(v):
    if instanceof(v, dict):
        if '__type' not in v:
             return {'__type': 'dict', 'data': [[key,value] for key,value in v.items()]}
    raise TypeError # Use default json processing for this value
```

This would allow encoding any dict whose key is json serializable. As you point out, the existing `object_hook` of the decoder would be sufficient to transform values back to dict.

If you still think a `preprocess` parameter is not useful enough to add to simplejson, what do you think about overriding encode in my encoder, to _add a a wrapper around all nested dict_ so they would have a for_json method that essentially does what preprocess above would do? Is this what you meant in your suggestion?

``` python
def encode(self, o): 

    def for_json(self):
        return {'__type': 'dict', 'data': [[key,value] for key,value in v.items()]}

    # traverse o recursively (both, dicts and iterables) and every time you find a dict that does not contain the key __type, bind the for_json method to it
    ...
    
    return super().encode(o)
```

Thank you again.

**Comment by etrepum** [comment]
The if branch is probably something that could be lived with if it provided enough utility, but I think the performance impact of actually using this functionality would be pretty high and not particularly useful for most people. simplejson is 18 years old, I don't recall anyone ever asking to customize how dicts are encoded before this.

By wrapping what I meant is that in the RAD framework it would use some class to wrap dictionaries before they are passed to the encoder and the encoding logic/branching can be dealt with there.

Subclassing the encoder won't really help you, there's nothing in there that would let you change the behavior for any nested data structures. None of that happens with method dispatch.

**Comment by jmoraleda** [comment]
@etrepum Thank you for your feedback. I have come to the conclusion, that you are right: The feature is sufficiently rare that the correct tradeoff is for users of the framework to explicitly use a custom class that implements `for_json` when using dicts where the keys are not strings rather than adding extra complexity to processing all dicts for the sake of making the feature fully transparent.

 In case others come here, and this is helpful, this is the custom class that I am using

``` python
class AnyKeyDict(dict):
    ''' Dict where JSON serialization and deserialization are inverse
    operations of each other even when keys are not Strings (as long as they are json-serializable)
 
    Remark that a "regular" dict serializes keys in json by converting them to String, which
    means deserializing it produces a different Map from the original, since the original non-string keys 
    are replaced by their stringified versions '''
    def for_json(self):
        ''' Encoding hook for simplejson - not available in default json library '''
        return { _TYPE: C.type_value.any_key_map,
                 _SINGLE_VALUE_PROPERTY: [[k,v] for k,v in self.items()] }
```
