### ISSUE TITLE
Django v1.8 and Django Select2 v4.3.1, sometimes an ImportError occurs

### ISSUE THREAD

**Issue by ST-EXC** [simplejson/simplejson#327]
When using Django v1.8 and Django Select2 v4.3.1, sometimes an ImportError occurs: unable to import SimpleJSON. This error message indicates that the SimpleJSON module cannot be imported, which may limit or render certain features of Django unusable.

**Comment by etrepum** [comment]
This is not an error message from simplejson, nothing we can do about it.
