### ISSUE TITLE
use __json__ attribute to encode custom objects

### ISSUE THREAD

**Issue by chason** [simplejson/simplejson#52]
I'm currently working on an issue where I'm writing a library that will interface with other moving parts that use simplejson internally. However, I need to be able to pass them a custom object and have that be serialized. Unfortunately, since the json encoding is done within these projects and isn't directly called by my code, I can't pass it a custom encoder.

Pyramid (one of the moving parts I'm using) has a useful function that will use the **json** attribute to encode a custom object, but the other one I'm using does not have that. While searching around, I found [this patch](http://code.google.com/p/simplejson/issues/detail?id=32&can=1) from the code.google.com repo.

It would be awesome if this behavior could be included in simplejson by default. The current behavior of using the output from repr(o) makes it very difficult to have my object serializable by simplejson in an agnostic manner, since I'm not working with the library directly.

**Comment by AlJohri** [comment]
@etrepum @shakefu would you consider allowing the `for_json` parameter of dumps to accept a string of the name of the method in addition to a bool? if the value is True, it continues to do the current behavior of calling `for_json` on the object. If the value is a string, it calls the method by that name instead (such as dunder json, `__json___`).

**Comment by etrepum** [comment]
If there was a well tested PR and some significant examples of __json__ usage in the wild that made it compelling.

**Comment by AlJohri** [comment]
Not very scientific, but, searching github restricted to repositories tagged as python yields:

[`__json__`](https://github.com/search?l=Python&q=__json__&type=Code&utf8=%E2%9C%93) - 4,034 instances
[`for_json`](https://github.com/search?l=Ruby&q=for_json&ref=searchresults&type=Code&utf8=%E2%9C%93) - 3,856 instances

**Comment by serhiy-storchaka** [comment]
Special methods starting and ending with double underscores are reserved for Python interpreter. If once the standard json module would support special attribute to encode custom objects, it would likely be named __json__. But it's signature can be different.

**Comment by jaraco** [comment]
>  If once the standard json module would support special attribute to encode custom objects, it would likely be named `__json__`. But it's signature can be different.

This point seems like an argument _for_ using `__json__`, but with the additional caveat that the protocol should be presented in a PEP and accepted first, so that the signature can be formalized and tools like `simplejson` can rely on the same protocol.

**Comment by Alexhuszagh** [comment]
@jaraco It really isn't, since if the `_json__` implementation differed at all from whats simplejson used (say, it didn't return a JSON-encodable object, but returned str or bytes, the actually encoded JSON), then simplejson would have to break backwards compatibility and break user code. If `__json__` is ever used by the Python interpreter, then you can implement `__json__` as `for_json`.
